---

name: Releases

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ksm2/archive-action@v1
        with:
          format: "tar.gz"
          name: "iocage-${{ github.ref_name }}"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "iocage-${{ github.ref_name }}.tar.gz"
#        bodyFile: "body.md"
