name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ksm2/archive-action@v1
      with:
      format: "tar.gz"
      name: "iocage-${GITHUB_REF##*/}.tar.gz"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "iocage-${GITHUB_REF##*/}.tar.gz"
#        bodyFile: "body.md"
